#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Install and configure HAproxy on my lb-01 server

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  kokainaW_frontend
        bind *:80
        mode http
        default_backend kokainaW_backend
backend kokainaW_backend
        balance roundrobin
        server 336555-web-01 100.25.197.24:80 check
        server 336555-web-02 54.236.25.9:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
