#!/usr/bin/env bash
# SSH client

Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    GSSAPIDelegateCredentials no
